---
- hosts: servers
  remote_user: ec2-user

  tasks:
    - name: Ensure inventory file at remnote machine has right permissions and user/group
      file: path=/opt/inventory owner=root group=root mode=0666
      sudo: yes

    - name: Create a directory under opt
      file: path=/opt/dagada state=directory owner=ec2-user group=ec2-user mode=0777
      sudo: yes

    - name: Create a file under opt
      file: path=/opt/dagada1 state=touch owner=ec2-user group=ec2-user mode=0777
      sudo: yes
